@api = http://localhost:3000

//---------------USERS--------------------
### GET USERS
GET {{api}}/users

### GET USER BY ID
GET http://localhost:3000/users/1

### POST USER
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "ian",
    "email": "ian@gmail.com"
}

### DELETE USER
DELETE http://localhost:3000/users/3

### PUT USER 
PUT http://localhost:3000/users/4
Content-Type: application/json

{
    "name": "ian",
    "email": "ianrivas@gmail.com"
}

//---------------OPERATIONS--------------------

### GET OPERATIONS BY ID (userid params)
GET http://localhost:3000/operations/1

### CREATE OPERATIONS (userid params)
POST http://localhost:3000/operations/1
Content-Type: application/json

{
    "concepto": "netflix",
    "monto": "1000",
    "fecha": "2021-10-24",
    "tipo": "ingreso"
}

### DELETE OPERATIONS (id params)
DELETE http://localhost:3000/operations/1

### PUT USER  (id params)
PUT http://localhost:3000/operations/2
Content-Type: application/json

{
    "concepto": "netflix",
    "monto": "1200",
    "fecha": "2021-10-24",
    "tipo": "ingreso"
}